import Head from 'next/head'
import Swiper from '../components/Swiper'
import FilmList from '../components/FilmList'
import Slider from '../components/Slider'

export default function Home() {
  return (


    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swiper/>
      <FilmList data={'Trend'}/>
      <FilmList data={'Popular'}/>
      <Slider />
      <FilmList data={'Most Liked'}/>
      {/* <FilmList data={trend} title={'Trend Videos'} url={'url'}/>
      <FilmList data={trend} title={'Popular Videos'} url={'url'}/>
      <FilmList data={trend} title={'Recent Videos'} url={'url'}/> */}

    </>
  )
}
