import Head from "next/head";
import Swiper from "../components/swiper/Swiper";
import FilmList from "../components/filmlist/FilmList";
import Slider from "../components/slider/Slider";
import { useState, useEffect } from "react";

export default function Home({ filmData1, filmData2, filmData3 }) {
  const [width, setWidth] = useState();
  useEffect(() => {
    const handleResize = () => setWidth(window.innerWidth);
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swiper filmData={filmData1} play={true} />
      <FilmList data={"Trend"} filmData={filmData1} width={width} />
      <FilmList data={"Popular"} filmData={filmData2} width={width} />
      <Slider filmData={filmData2} play={false} />
      <FilmList data={"Most Liked"} filmData={filmData3} width={width} />
    </>
  );
}

export const getServerSideProps = async () => {
  const page1 = Math.ceil(Math.random() * 20);
  const page2 = Math.ceil(Math.random() * 20);
  const page3 = Math.ceil(Math.random() * 20);

  const res1 = await fetch(`https://api.themoviedb.org/3/trending/all/week?api_key=${process.env.DB_KEY}&page=${page1}&language=tr-TR`);
  const filmData1 = await res1.json();
  const res2 = await fetch(`https://api.themoviedb.org/3/trending/all/week?api_key=${process.env.DB_KEY}&page=${page2}&language=tr-TR`);
  const filmData2 = await res2.json();
  const res3 = await fetch(`https://api.themoviedb.org/3/trending/all/week?api_key=${process.env.DB_KEY}&page=${page3}&language=tr-TR`);
  const filmData3 = await res3.json();

  const response = await fetch(`https://api.themoviedb.org/3/genre/movie/list?api_key=${process.env.DB_KEY}&language=en-EN`);
  const genres = await response.json();



  return {
    props: {
      filmData1,
      filmData2,
      filmData3,
    },
  };
};
